name: Main branch

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
     
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test rat package
      run: |
        cd pkg/rat/ && go mod tidy && go test -v -cover > tests.results
        cat tests.results
        PERCENTAGE=$(cat tests.results | tail -2 | head -1 | awk '{printf $2}' | head -c 2)
        if [ "${PERCENTAGE}" -lt "90" ]; then
            echo "Code coverage ($PERCENTAGE%) is not high enough";
            exit 1
        fi

    - name: Test cmdLineParser package
      run: cd pkg/cmdLineParser/ && go mod tidy && go test -v

    - name: Build cmd
      run: cd cmd/rat/ && go mod tidy && go build -v
    
    - name: Test end-to-end
      run: |
        cd cmd/rat/
        ./main /tmp/out.rat ../../tests/input_files/
        ./main -x /tmp/out.rat
