name: Main branch

on:
  push:

jobs:
  build-and-test:
     
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build cmd
      run: cd cmd/rat/ && go mod tidy && go build -v

    - name: Test rat package
      run: cd pkg/rat/ && go mod tidy && go test -v

    - name: Test cmdLineParser package
      run: cd pkg/cmdLineParser/ && go mod tidy && go test -v
    
    - name: Test end-to-end
      run: |
        cd cmd/rat/
        ./main /tmp/out.rat ../../tests/input_files/testData.json
        cmp --silent /tmp/out.rat ../../tests/expected_files/out.rat
        if [ $? -ne 0 ]; then
          echo "E2E failed: RAT file is not as expected"
          exit 1
        fi
